### ISSUE TITLE
JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset flaky

### ISSUE THREAD

**Issue by raboof** [apache/pekko-projection#104]
This test appears to be flaky:

```
--> [org.apache.pekko.projection.jdbc.JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset] Start of log messages of test that failed with expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[2024-02-07 19:15:35,185] [DEBUG] [JdbcProjectionTest] [] [pool-6-thread-5] - Starting ActorTestKit MDC: {}
[2024-02-07 19:15:35,185] [INFO] [org.apache.pekko.actor.testkit.typed.javadsl.LogCapturing] [] [pool-6-thread-5] - Logging started for test [org.apache.pekko.projection.jdbc.JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset] MDC: {}
<-- [org.apache.pekko.projection.jdbc.JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset] End of log messages of test that failed with expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[info] - atLeastOnceShouldRestartFromPreviousOffset *** FAILED ***
[info]   org.junit.ComparisonFailure: expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[info]   at org.junit.Assert.assertEquals(Assert.java:117)
[info]   at org.junit.Assert.assertEquals(Assert.java:146)
[info]   at org.apache.pekko.projection.jdbc.JdbcProjectionTest.lambda$atLeastOnceShouldRestartFromPreviousOffset$1cd53367$1(JdbcProjectionTest.java:351)
[info]   at org.apache.pekko.projection.testkit.javadsl.ProjectionTestKit.$anonfun$runWithTestSink$1(ProjectionTestKit.scala:108)
[info]   at org.apache.pekko.projection.testkit.javadsl.ProjectionTestKit.$anonfun$runWithTestSink$1$adapted(ProjectionTestKit.scala:108)
[info]   at org.apache.pekko.projection.testkit.scaladsl.ProjectionTestKit.runWithTestSink(ProjectionTestKit.scala:136)
[info]   at org.apache.pekko.projection.testkit.javadsl.ProjectionTestKit.runWithTestSink(ProjectionTestKit.scala:108)
[info]   at org.apache.pekko.projection.jdbc.JdbcProjectionTest.atLeastOnceShouldRestartFromPreviousOffset(JdbcProjectionTest.java:340)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[info]   at org.apache.pekko.actor.testkit.typed.javadsl.LogCapturing$$anon$1.evaluate(LogCapturing.scala:58)
[info]   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[info]   at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[info]   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[info]   at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[info]   at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[info]   at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[info]   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[info]   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[info]   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[info]   at org.junit.runners.Suite.runChild(Suite.java:128)
[info]   at org.junit.runners.Suite.runChild(Suite.java:27)
[info]   at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[info]   at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[info]   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
[info]   at org.scalatestplus.junit.JUnitSuiteLike.run(JUnitSuiteLike.scala:241)
[info]   at org.scalatestplus.junit.JUnitSuiteLike.run$(JUnitSuiteLike.scala:229)
[info]   at org.scalatestplus.junit.JUnitSuite.run(JUnitSuite.scala:71)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:153)
[info]   at sbt.TestRunner.run(TestFramework.scala:168)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:336)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:296)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:336)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:336)
[info]   at sbt.TestFunction.apply(TestFramework.scala:348)
[info]   at sbt.Tests$.$anonfun$toTask$1(Tests.scala:436)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:47)
[info]   at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[info]   at sbt.Execute.work(Execute.scala:292)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Roiocam** [comment]
Closed with #108

**Comment by raboof** [comment]
Seen again in #281 - perhaps this fix needs to be applied to yet another test?

```
JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset] End of log messages of test that failed with expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[info] - atLeastOnceShouldRestartFromPreviousOffset *** FAILED ***
[info]   org.junit.ComparisonFailure: expected:<abc|def|[ghi|]> but was:<abc|def|[]>
```

**Comment by pjfanning** [comment]
today
```
<-- [org.apache.pekko.projection.jdbc.JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset] End of log messages of test that failed with expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[info] - atLeastOnceShouldRestartFromPreviousOffset *** FAILED ***
[info]   org.junit.ComparisonFailure: expected:<abc|def|[ghi|]> but was:<abc|def|[]>
```
